# Generated by Django 2.2.1 on 2019-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_id', models.SmallIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
