# Generated by Django 2.2.1 on 2019-05-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchmodel',
            name='severity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
